### ISSUE TITLE
clinet gives error 

### ISSUE THREAD

**Issue by ghost** [AsertCreator/NetBlox#2]
[Fri, 13 Sep 2024 21:18:37 GMT][nb-info] NetBlox Client (16.15.1) is running...
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NetBlox.Client.Program.Main(String[] args) in D:\a\NetBlox\NetBlox\UniversalClient\Program.cs:line 15
idk why i fixed my self but why does not work for u

**Comment by AsertCreator** [comment]
the client wrongly assumes to have some parameters, when it doesnt. im aware of this and fix had already been pushed on application branch and maybe soon it will be on master.

**Comment by ghost** [comment]
but why are u making a clone in the frist place

**Comment by AsertCreator** [comment]
bc why not

**Comment by ghost** [comment]
BUT CAN U FIX THE REGISTER LOGIN THING FOR MY CLONE IT'S THE SAME to yours

**Comment by ghost** [comment]
AND MAKE MY SERVER SERVEABLE AND PUBLIC SERIVE BETTER AND CLINET AND STUIDO STUFF

**Comment by AsertCreator** [comment]
please calm down. the game is very raw, almost nothing works properly or by design, and i am fully aware of this. the login/register and game launching/installation are all coming soon. 

currently, the priority is to enchance the client experience, to solve all networking and physics problems. you can start simulated server/client configuration in visual studio.

**Comment by AsertCreator** [comment]
everything will come, but dont expect for it to come like tomorrow or even this month. i am the only contributor to the project.

**Comment by ghost** [comment]
but cheak this https://www.youtube.com/watch?v=o9wEtYS95B4

**Comment by AsertCreator** [comment]
> but cheak this https://www.youtube.com/watch?v=o9wEtYS95B4

i absolutely do not like how you renamed the project and putting it as your own. i would appreciate if you switched the license back to MIT, with me credited.

**Comment by AsertCreator** [comment]
if you come up with good ideas and their implementations, please file a pull request
