### ISSUE TITLE
> but cheak this https://www.youtube.com/watch?v=o9wEtYS95B4

### ISSUE THREAD

**Issue by ghost** [AsertCreator/NetBlox#4]
> but cheak this https://www.youtube.com/watch?v=o9wEtYS95B4

i absolutely do not like how you renamed the project and putting it as your own. i would appreciate if you switched the license back to MIT, with me credited.

_Originally posted by @AsertCreator in https://github.com/AsertCreator/NetBlox/issues/2#issuecomment-2350918308_

https://github.com/rbxl-games101/NCR/blob/main/README.md be happy now sory

**Comment by ghost** [comment]
am realy realy realy sory to you  i have some times gred but ill stop

**Comment by ghost** [comment]
but it's MIT forgot about that

**Comment by ghost** [comment]
i cant pull req

**Comment by AsertCreator** [comment]
thats nice. please stop creating issues and have a good day

**Comment by AsertCreator** [comment]
> i cant pull req

because NCR repository is not a fork, as it was supposed to be

**Comment by ghost** [comment]
ok but this is best roblox clone i seeen but revome bad words form the readme.mc

**Comment by ghost** [comment]
i game a mod off your game

**Comment by ghost** [comment]
but i livee in sweden

**Comment by ghost** [comment]
can i be cuntebuter pls i can help

**Comment by AsertCreator** [comment]
> can i be cuntebuter pls i can help

fork this project, if you didnt already. push commits to your fork. file PR according to github documentation
