### ISSUE TITLE
[FEATURE] ADD BETTER FRONTEND AND FAST API

### ISSUE THREAD

**Issue by ghost** [AsertCreator/NetBlox#7]
**Feature description**
- please consisely describe the feature that you'd like to see here.
- it will be better for and better api and forntend for netblox

**Argumentation**
- why does this feature have to exist in the first place?
- it helps other players to play games and be happy 

**Additional context**
- what do you think can be helpful for us when implementing this feature?
- making it esay to start and make game in netblox

**Comment by AsertCreator** [comment]
if you mean the public service, then its not the priority. current thing is want to implement normally is physics, and maybe then i will start working on the PS. everything will come, please wait

**Comment by ghost** [comment]
@AsertCreator ok but how long will it take will it take a year or so

**Comment by ghost** [comment]
can u add /user/id and /register when not login in and /create/game/id
